### ISSUE TITLE
jam --version doesn't match jam Github Release version

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/jam#22]
## What happened?

* What were you attempting to do?
I wanted to download the latest version of jam, then check the version I'd downloaded with `jam --version`. I downloaded the `jam-darwin` artifact attached to the [v1.1.0 release](https://github.com/paketo-buildpacks/jam/releases/tag/v1.1.0).

* What did you expect to happen?
I expected the printed version to match the version on the release I'd downloaded.

* What was the actual behavior? Please provide log output, if possible.
```bash
jam version
jam 1.0.3
```

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
This appears to have been a mistake by whomever released the `1.1.0` version of `jam`. It looks like the draft release had been run to build `1.0.3` since the previous version had been `1.0.2` and we default to creating a patch release. Instead of recreating the release, it looks like we just changed the version on the release page and then released it. This clearly didn't change the version that was baked into the binary.

**Comment by fg-j** [comment]
For buildpacks, there's a step added to the "Push buildpackage" workflow that ensures a similar version mismatch doesn't happen: https://github.com/paketo-buildpacks/github-config/blob/9304e778e060ce04f111fa884bdfb84c0ef6e263/implementation/.github/workflows/push-buildpackage.yml#L28

I think we should add a post-release workflow on this repo that will complain if the baked in version doesn't match the Github release version.
